server:
  port: 8080

spring:
  datasource:
    username: root
    password: sa123
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.141.169:3306/test?useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    minIdle: 5
    initialSize: 5
    maxActive: 20
